name: wemake-python-styleguide
on:
  pull_request
jobs:
  build:
    name: wemake
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        uses: wemake-services/wemake-python-styleguide@0.13.4
